export ARTIFACTORY="https://qartifactory-edge.qualcomm.com/artifactory/qsc_releases/software/chip/component/camx.qclinux.0.0"
export TAG="260724"
export DISTRO="prebuilt_trixie"
export PACKAGE_NAME="camxfirmware_1.0.1_arm64.tar.gz"
