export ARTIFACTORY="https://qartifactory-edge.qualcomm.com/artifactory/qsc_releases/software/chip/component/camx.qclinux.0.0"
export TAG="260703"
export DISTRO="prebuilt_resolute"
export PACKAGE_NAME="camxfirmware_1.0.0_arm64.tar.gz"
